[[players]]
wall_that_gives_points = "Right"

[[players.moves]]
key = "Q"

[players.moves.effect]
Move = [0.0, 1.0, 0.0]

[[players.moves]]
key = "A"

[players.moves.effect]
Move = [0.0, -1.0, 0.0]

[[players]]
wall_that_gives_points = "Left"

[[players.moves]]
key = "O"

[players.moves.effect]
Move = [0.0, 1.0, 0.0]

[[players.moves]]
key = "L"

[players.moves.effect]
Move = [0.0, -1.0, 0.0]

[paddle]
width = 20
height = 120
speed = 500.0

[distribution]
up_direction = [0.0, 1.0, 0.0]
down_direction = [0.0, -1.0, 0.0]
gap_between_paddle_and_side_wall = 100
gap_between_paddle_and_horizontal_wall = 10
minimum_gap_between_paddle_and_goal_bricks = 20
gap_between_bricks = 1
minimum_gap_between_bricks_and_horizontal_walls = 20
minimum_gap_between_bricks_and_vertical_walls = 40

[ball]
starting_position = [0.0, -50.0, -1.0]
starting_direction = [0.5, -0.5]
speed = 400.0
max_speed = 2000.0
size = [30.0, 30.0, 0.0]
probability_to_duplicate = 0.10000000149011612
padding_for_bounds = 0.10000000149011612

[wall]
thickness = 10
x_left_wall = -600
x_right_wall = 600
y_down_wall = -300
y_up_wall = 300

[brick]
width = 5
height = 10

[scoreboard]
font_size = 40.0

[scoreboard.text_padding]
Px = 5.0

[colors.background.Rgba]
red = 0.8999999761581421
green = 0.8999999761581421
blue = 0.8999999761581421
alpha = 1.0

[colors.paddle.Rgba]
red = 0.30000001192092896
green = 0.30000001192092896
blue = 0.699999988079071
alpha = 1.0

[colors.ball.Rgba]
red = 1.0
green = 0.5
blue = 0.5
alpha = 1.0

[colors.brick.Rgba]
red = 0.5
green = 0.5
blue = 1.0
alpha = 1.0

[colors.wall.Rgba]
red = 0.800000011920929
green = 0.800000011920929
blue = 0.800000011920929
alpha = 1.0

[colors.text.Rgba]
red = 0.5
green = 0.5
blue = 1.0
alpha = 1.0

[colors.score.Rgba]
red = 1.0
green = 0.5
blue = 0.5
alpha = 1.0
